resolver: lts-8.13

packages:
- '../motyhub-base'
- '../motyhub-db'
- '../motyhub-crawler'
- '.'

extra-deps:
- servant-0.10
- servant-server-0.10
- persistent-relational-record-0.1.0.0
- xml-html-conduit-lens-0.3.2.3

extra-package-dbs: []
